### PR TITLE
Update the signal handling API for the unstable

### PR DESCRIPTION
**Pull request by aignas**
Hello,

I have found some time and wanted to update the signal handling API for the unstable branch. What concerns signals should be working now.

Cheers,
    Ignas

PS. There are 3 previous commits also, as they are in master branch and should be also be in the unstable. If I am doing something wrong with these 3 commits, please let me know.

### CODE REVIEW

**Comment by bioe007** [comment]
'This pull request cannot be automatically merged.'

[panic]
ohnoes!
[/panic]

I think commit: ffdcd1eb9 already applies the capi.\* prefixing. That was from a
previous commit of yours - I did amend it to include the miss from 25df071.

Perhaps you can check out unstable, then apply be05dde and fd787f0, then it
should be merge-able.

Also foldmarkers have been gone since f90bf738ca.

If you don't have time and I get to this then I'll just cherry-pick your commits and push from my box.

Thanks.

**Comment by aignas** [comment]
Hi, sorry, I have no idea how I missed the notification from Github. Sorry about that...

Actually it was hard to find any free time due to studies and now I have more time.

I also had some problems with git branches, and somehow I did not see the mentioned commits in your unstable branch. And I can confirm, that I can not see the mentioned commits in the unstable branch. They are on master, but they are not present on the unstable branch.

I checked that on github and unstable is shown to be lagging by 2 commits.

Do you have any ideas?

Cheers.

**Comment by aignas** [comment]
I have almost untangled all the mess I had. And I understood the way Github manages the pull requests. It basically updates the commits automatically, so I can not actually remove the commits. I guess, that you should update your unstable branch (i.e. f90bf73 and ae5792e commits).

Then I can fix the rest, so that you would have a nice pull request with only two commits.

Cheers,
I.

**Comment by aignas** [comment]
Hi Perry,

could you wait a bit until you merge this thing, as I believe, that more signals are needed, and maybe it would make more sense if I somehow achieve shifty to be working with the master branch and then there will be one big merge.

So I guess, that I can close this, as it is not full by any means and everything should be tackled slightly differently.

Feel free to reopen, if you think differently.

**Comment by bioe007** [comment]
On Tue, Dec 20, 2011 at 9:52 AM, Ignas Anikevicius
reply@reply.github.com
wrote:

> Hi Perry,
> 
> could you wait a bit until you merge this thing, as I believe, that more signals are needed, and maybe it would make more sense if I somehow achieve shifty to be working with the master branch and then there will be one big merge.
> 
> So I guess, that I can close this, as it is not full by any means and everything should be tackled slightly differently.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bioe007/awesome-shifty/pull/9#issuecomment-3222453

Ack.

I freaked earlier when I went looking to merge this (before reading
this e-mail) and couldn't find the pull request anymore. I was like
"Wat, did I break something?"

## 

perry

**Pull request closed without merging**
